# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

    redirect_register_user.registration.completed:
        class: CA\ForumBundle\EventListner\RegistrationConfirmedListner
        arguments: ["@router"]
        tags:
            - { name: kernel.event_subscriber }
